### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serialize' 

### ISSUE THREAD

**Issue by ruyijidan** [giranntu/NVIDIA-TensorRT-Tutorial#1]
file.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize' 

I use torchvision model and arcface model are same error,use the demo model is ok!
 maybe the *.onnx have some problem.

**Comment by ruyijidan** [comment]
but i conver the pth file to onnx file is ok,the onnx file can infer

**Comment by giranntu** [comment]
@ruyijidan  Good catch. 
please refer the new update for the solutions. :_)
